include: package:flutter_lints/flutter.yaml
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "lib/generated_plugin_registrant.dart"
    - "lib/src/l10n/messages_*.dart"
    - "lib/src/models/*.g.dart"
    - "lib/src/models/*.freezed.dart"

  errors:
    invalid_annotation_target: ignore

dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    number-of-parameters: 4
    source-lines-of-code: 50
  metrics-exclude:
    - test/**
  rules:
    - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    - prefer-trailing-comma:
        severity: error
    - prefer-conditional-expressions
    - no-equal-then-else

linter:
  rules:
